version: '2.3'

services:
  tf-serving:
    build: tf-serving
    runtime: nvidia
    ipc: host
    environment:
      - NVIDIA_VISIBLE_DEVICES=0
    networks:
    - front

  pytorch-chatbot:
    build: pytorch-chatbot
    # Uncomment to run service on additional GPU. Use CPU by default

    # runtime: nvidia
    # ipc: host
    # environment:
    # - NVIDIA_VISIBLE_DEVICES=1

    networks:
      - front

  vkbot:
    build: .
    command: supervisord -c /app/etc/supervisord.ini
    networks:
     - front
    environment:
     - PYTHONASYNCIODEBUG=0
     - VK_APP_SECRET
     - VK_ACCESS_TOKEN
     - SENTRY_DSN
    volumes:
     - ./vkbot:/app/vkbot
     - ./etc:/app/etc
     - ./tests:/app/tests
     - aiohttp-sockets:/var/lib/aiohttp
    depends_on:
     - tf-serving
     - pytorch-chatbot

  nginx:
    image: nginx:latest
    ports:
     - 80:80
    environment:
     - TZ=Europe/Moscow
    networks:
     - front
    volumes:
     - ./etc/nginx.conf:/etc/nginx/nginx.conf
     - aiohttp-sockets:/var/lib/aiohttp
    depends_on:
     - vkbot

networks:
  front:

volumes:
  aiohttp-sockets: